### ISSUE TITLE
Trackpad issue in macOS Monterey 12.2.1

### ISSUE THREAD

**Issue by quynkk1** [misa198/dell-latitude-5570-hackintosh#14]
EN: I have updated from macOS 11.6.2 to macOS 12.2.1 and I have trackpad issue.
It stopped working after using several minutes, I need to force restart computer and changed VoodooPS2 (v1.0.6) from @SkyrilHD into default Acidanthera's VoodooPS2. Do you have this issue on your hack?
Log: [panic.log.txt](https://github.com/misa198/dell-latitude-e5570-hackintosh/files/8176182/panic.log.txt)
 
 VN: Sau khi update macOS từ 11.6.2 lên 12.2.1 và phát hiện lỗi trackpad. Tầm dùng được vài phút là bị dính panic nên phải tắt nóng máy đi rồi khởi động lại mới dùng tiếp được. Bạn có gặp lỗi này trên máy của b ko?

**Comment by misa198** [comment]
Mình cũng bị. Thi thoảng treo hẳn máy luôn, thi thoảng chỉ dùng được trục x, thi thoảng mất trackpad. Mình check issue bên repo của SkyrilHD thì cũng có người bị.
Mình tạo issue bên đấy thì ông ấy có bảo đổi qua bản debug rồi cung cấp log cho ông ấy. Nhưng sau khi reset nvram thì từ bấy đến giờ  không bị nữa.

**Comment by quynkk1** [comment]
Của mình thử bản 1.0.6 với debug 1.0.7 đều bị. Reset NVRAM rồi nhưng vẫn bị nên switch về kext default của Acidanthera luôn

**Comment by misa198** [comment]
Bạn đã thử bản VoodooPS 2.2.8 vừa release hôm qua của Acidanthera chưa. Bạn có gặp lỗi gì không. SkyrilHD thông báo repo của ông sẽ hợp nhât với Acidanthera. MÌnh dùng thì đang gặp lỗi.

**Comment by quynkk1** [comment]
Theo như mình được biết là cái VoodooPS2 ALPS của SkyrilHD thì hiện tại chỉ hoạt động từ bản 12.1 đổ về, bản 12.2 trở đi sẽ bị Panic. Mình downgrade từ 12.2.1 về 12.1 và 12.0.1 thì hoạt động ổn không có lỗi

**Comment by misa198** [comment]
Mình đang dùng VoodooPS2 của SkyrilHD với 12.2.1 và vẫn hoạt động ổn định mà.

![Screen Shot 2022-03-09 at 13 53 51](https://user-images.githubusercontent.com/51451216/157388523-6a8e94c6-8eeb-422a-a702-3ba3c96aa534.png)

**Comment by quynkk1** [comment]
Solved with new VoodooPS2 from Acidanthera.
